/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/occupancy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Occupancy */
        get: operations["occupancy_occupancy_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/forecast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Forecast */
        get: operations["forecast_forecast_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recommend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recommendation */
        post: operations["recommendation_recommend_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Candidate */
        Candidate: {
            /**
             * Start Time
             * Format: date-time
             */
            start_time: string;
            /**
             * End Time
             * Format: date-time
             */
            end_time: string;
            facility_id: components["schemas"]["FacilityId"];
            /** Facility Name */
            facility_name: string;
            /** Predicted Occupancy Pct */
            predicted_occupancy_pct: number;
            /**
             * Confidence
             * @enum {string}
             */
            confidence: "low" | "medium" | "high";
            /**
             * Provenance
             * @enum {string}
             */
            provenance: "demo" | "live" | "cached" | "unavailable";
            /**
             * Exceeds Tolerance
             * @default false
             */
            exceeds_tolerance: boolean;
        };
        /** ErrorDetail */
        ErrorDetail: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Details */
            details?: unknown;
        };
        /** ErrorResponse */
        ErrorResponse: {
            error: components["schemas"]["ErrorDetail"];
        };
        /** FacilityForecast */
        FacilityForecast: {
            /** Forecast Source */
            forecast_source?: ("databricks" | "collector_fallback") | null;
            facility_id: components["schemas"]["FacilityId"];
            /** Facility Name */
            facility_name: string;
            /** Points */
            points: components["schemas"]["ForecastPoint"][];
            /** Generated At */
            generated_at: string | null;
            /** Observed At */
            observed_at: string | null;
            /**
             * Confidence
             * @enum {string}
             */
            confidence: "low" | "medium" | "high";
            /**
             * Provenance
             * @enum {string}
             */
            provenance: "demo" | "live" | "cached" | "unavailable";
            /**
             * Stale
             * @default false
             */
            stale: boolean;
        };
        /**
         * FacilityId
         * @enum {string}
         */
        FacilityId: "mccomas" | "war_memorial";
        /** ForecastPoint */
        ForecastPoint: {
            /**
             * Forecast Time
             * Format: date-time
             */
            forecast_time: string;
            /** Predicted Occupancy Pct */
            predicted_occupancy_pct: number;
        };
        /** ForecastResponse */
        ForecastResponse: {
            /** Facilities */
            facilities: components["schemas"]["FacilityForecast"][];
            /**
             * Data Mode
             * @enum {string}
             */
            data_mode: "demo" | "live";
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /**
             * Data Mode
             * @enum {string}
             */
            data_mode: "demo" | "live";
            /** Integrations */
            integrations: {
                [key: string]: components["schemas"]["IntegrationStatus"];
            };
        };
        /** IntegrationStatus */
        IntegrationStatus: {
            /** Configured */
            configured: boolean;
            /**
             * Status
             * @enum {string}
             */
            status: "not_configured" | "not_implemented" | "ready" | "unavailable";
        };
        /** Interval */
        Interval: {
            /**
             * Start Time
             * Format: date-time
             */
            start_time: string;
            /**
             * End Time
             * Format: date-time
             */
            end_time: string;
        };
        /** Occupancy */
        Occupancy: {
            /**
             * Opening Status
             * @default unknown
             * @enum {string}
             */
            opening_status: "open" | "closed" | "unknown";
            /** Opens At */
            opens_at?: string | null;
            /** Closes At */
            closes_at?: string | null;
            facility_id: components["schemas"]["FacilityId"];
            /** Facility Name */
            facility_name: string;
            /** Occupancy */
            occupancy?: number | null;
            /** Remaining */
            remaining?: number | null;
            /** Capacity */
            capacity?: number | null;
            /** Occupancy Pct */
            occupancy_pct?: number | null;
            /** Observed At */
            observed_at?: string | null;
            /** Source Updated At */
            source_updated_at?: string | null;
            /**
             * Provenance
             * @enum {string}
             */
            provenance: "demo" | "live" | "cached" | "unavailable";
            /**
             * Stale
             * @default false
             */
            stale: boolean;
        };
        /** OccupancyResponse */
        OccupancyResponse: {
            /** Facilities */
            facilities: components["schemas"]["Occupancy"][];
            /**
             * Data Mode
             * @enum {string}
             */
            data_mode: "demo" | "live";
        };
        /** RecommendationRequest */
        RecommendationRequest: {
            /**
             * Start Time
             * Format: date-time
             */
            start_time: string;
            /**
             * End Time
             * Format: date-time
             */
            end_time: string;
            /** Unavailable */
            unavailable?: components["schemas"]["Interval"][];
            /**
             * Workout Duration Minutes
             * @default 75
             */
            workout_duration_minutes: number;
            /** Preferred Gyms */
            preferred_gyms?: components["schemas"]["FacilityId"][];
            /**
             * Crowd Tolerance
             * @default low
             * @enum {string}
             */
            crowd_tolerance: "low" | "medium" | "high";
        };
        /** RecommendationResponse */
        RecommendationResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "no_available_window" | "data_unavailable";
            recommendation?: components["schemas"]["Candidate"] | null;
            alternative?: components["schemas"]["Candidate"] | null;
            /** Explanation */
            explanation: string;
            /**
             * Method
             * @default deterministic
             * @enum {string}
             */
            method: "deterministic" | "gemini";
            /** Warnings */
            warnings?: string[];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /**
             * Data Mode
             * @enum {string}
             */
            data_mode: "demo" | "live";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: {
                demo?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    occupancy_occupancy_get: {
        parameters: {
            query?: {
                demo?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OccupancyResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    forecast_forecast_get: {
        parameters: {
            query?: {
                facility_id?: components["schemas"]["FacilityId"] | null;
                start_time?: string | null;
                end_time?: string | null;
                demo?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForecastResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    recommendation_recommend_post: {
        parameters: {
            query?: {
                demo?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecommendationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
